name: Fork Sync

on:
  schedule:
    - cron: '0 0 * * *' # once every day at midnight
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          token: ${{ secrets.AUTO_MERGE }}
          base: en
          head: en
